index/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    # path('add_sql/', add_sql),
    # re_path('^del/(.+)', del_sql, name='del_sql'),
    path('add_admin/', add_admin),
    path('imp/', server_import),
    path('login/', login),
    path('', login),
    path('index/', serverManage, name='index'),
    path('getServerList/', getServerList, name='getServerList'),
    # re_path('^index/(\d+)', index),
    path('add/', server_add, name='add'),
    path('handle_hard/', getSystemInfoHandler, name='handle_hard'),
    path('shell/', serverList, name='shell'),
    re_path('^del/(.+)', server_del, name='del'),
    re_path('^update/(\d+)', server_modify, name='update'),
    path('out/', SignOut),
    path('change/', server_pwd_change, name='change_pwd'),
    re_path('^webssh/(.+)', webssh, name='webssh'),
    path('ufile/', ufile, name='ufile'),
    re_path('^downfile/(.+)', downfile, name='downfile'),
    path('down_handler/', down_handler, name='down_handler'),
    path('tree/', serverListHandler),
    path('linux/', serverBatchRun),
    path('ed_pwd/', modifyUserPassword),
    re_path('^xshell/(.+)', getXshell, name='xshell'),
    re_path('^xftp/(.+)', getXftp, name='xftp'),
    path('project/', project, name='project'),
    path('edit_project/', edit_project, name='edit_project'),
    re_path('^obj_update/', obj_modify, name='obj_update'),
    re_path('^obj_hd/', obj_modify_handler, name='obj_hd'),
    re_path('^obj_del/(\d+)', obj_del, name='obj_del'),
    re_path('^obj_hander/', obj_hander, name='obj_hander'),
    re_path('^queue/', task_queue, name='queue'),
    re_path('^que_del/(\d+)', task_queue_del, name='que_del'),
    path('remark/', remark),
    path('getTemplate/', showServerTemplate, name='getTemplate'),
    path('addTemplate/', addServerTemplate, name='addTemplate'),
    path('delTemplate/', delServerTemplate, name='delTemplate'),
    path('tools/', small_tool, name='tools'),
    path('gettools/', get_tools, name='gettools'),
    path('showDatabase/', showDatabase, name='showDatabase'),
    path('showUrlMgm/', showUrlMgm, name='showUrlMgm'),
    path('showSupervisor/', showSupervisor, name='showSupervisor'),
    path('super/', super_handler, name='super'),
    path('getSuperConf/', getSuperConf, name='getSuperConf'),
    path('searchSuperConf/', searchSuperConf, name='searchSuperConf'),
    path('saveSuperConf/', saveSuperConf, name='saveSuperConf'),
    path('batch_edit/', batch_edit, name='batch_edit'),
    path('getProjectDeploymentRecord/', getProjectDeploymentRecord)

]

index/models.py
from django.db import models

"""
数据库说明：
null 是针对数据库而言，如果 null=True, 表示数据库的该字段可以为空。
blank 是针对表单的，如果 blank=True，表示你的表单填写该字段时可以不填
"""
TOPIC_CHOICE = (
    ('level1', 'Linux'),
    ('level2', 'Windows'),
    ('level3', '其他'))


class ProjectName(models.Model):  # 添加服务器分组类
    def __str__(self):
        return self.name

    uid = models.AutoField(primary_key=True, verbose_name='ID')  # 自增id
    name = models.CharField(max_length=30, verbose_name='项目名称')

    class Meta:
        verbose_name = "服务器项目组"  # 定义该实体类在 admin 中显示的名字(单数形式)
        verbose_name_plural = verbose_name  # 效果同上，是复数形式


class Group(models.Model):  # 添加服务器分组类
    def __str__(self):
        return self.name

    uid = models.AutoField(primary_key=True, verbose_name='ID')  # 自增id
    name = models.CharField(max_length=30, verbose_name='分组名称')

    class Meta:
        verbose_name = "服务器分组"  # 定义该实体类在 admin 中显示的名字(单数形式)
        verbose_name_plural = verbose_name  # 效果同上，是复数形式


class PassWord(models.Model):  # 添加服务器类
    def __str__(self):
        return self.hostname

    uid = models.AutoField(primary_key=True)  # 自增id
    hostname = models.CharField(max_length=30, verbose_name='主机名', null=True, blank=True)  # 主机名
    ctime = models.DateTimeField(auto_now=True, null=True)  # 时间
    system = models.CharField(max_length=20, null=True, verbose_name='系统', default='Linux', choices=TOPIC_CHOICE)  # 系统
    ip = models.CharField(verbose_name='IP地址', max_length=30, null=True, blank=True)  # ip
    intranet_ip = models.CharField(verbose_name='内网IP地址', max_length=30, null=True, blank=True)  # 内网ip
    user = models.CharField(max_length=20, verbose_name='高级用户名', null=True, blank=True)  # 账号
    password = models.CharField(max_length=300, verbose_name='密码', null=True, blank=True)  # 密码
    port = models.IntegerField(default=22, verbose_name='端口', null=True, blank=True)  # 端口
    group = models.ForeignKey(Group, null=True, on_delete=models.CASCADE, verbose_name='分组')
    projectName = models.ManyToManyField(ProjectName, blank=True, verbose_name='项目名称')
    system_info = models.CharField(max_length=20, verbose_name='系统版本', null=True, blank=True)  # 系统版本
    cpu_count = models.CharField(max_length=100, verbose_name='cpu核心数', null=True, blank=True)  # cpu信息
    cpu_info = models.CharField(max_length=100, verbose_name='cpu信息', null=True, blank=True)  # cpu信息
    mem_info = models.CharField(max_length=100, verbose_name='内存信息', null=True, blank=True)  # 内存信息
    hard_info = models.CharField(max_length=100, verbose_name='硬盘信息', null=True, blank=True)  # 硬盘信息
    status = models.CharField(max_length=100, verbose_name='状态', null=True, blank=True)  # 状态

    class Meta:
        verbose_name = "服务器信息"  # 定义该实体类在 admin 中显示的名字(单数形式)
        verbose_name_plural = verbose_name  # 效果同上，是复数形式


class remarks(models.Model):
    def __str__(self):
        return self.rep

    uid = models.AutoField(primary_key=True)
    rep = models.TextField()  # 备注信息
    host = models.ForeignKey(PassWord, null=True, on_delete=models.CASCADE, verbose_name='对应机器')  # 对应主机信息

    class Meta:
        verbose_name = "备注信息"  # 定义该实体类在 admin 中显示的名字(单数形式)
        verbose_name_plural = verbose_name  # 效果同上，是复数形式


class HostTmp(models.Model):
    datetime = models.DateTimeField(auto_now=True)
    unique = models.CharField(max_length=40, unique=True)
    host = models.CharField(max_length=32)
    port = models.IntegerField()
    user = models.CharField(max_length=32)
    auth = models.CharField(max_length=16)
    pkey = models.TextField(null=True, blank=True)
    password = models.CharField(max_length=180, null=True, blank=True)


class Object(models.Model):
    def __str__(self):
        return self.obj_name

    uid = models.AutoField(primary_key=True)
    obj_log = models.CharField(null=True, blank=True, max_length=200)
    obj_name = models.CharField(max_length=50)
    obj_text = models.TextField()

    class Meta:
        verbose_name = "项目模板"  # 定义该实体类在 admin 中显示的名字(单数形式)
        verbose_name_plural = verbose_name  # 效果同上，是复数形式


class Project(models.Model):
    def __str__(self):
        return self.name

    uid = models.AutoField(primary_key=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='分组')
    name = models.CharField(max_length=50, verbose_name='项目名称')
    host = models.ForeignKey(PassWord, null=True, on_delete=models.CASCADE, verbose_name='服务器')
    template = models.ForeignKey(Object, on_delete=models.CASCADE, verbose_name='模板')

    class Meta:
        verbose_name = "项目部署"  # 定义该实体类在 admin 中显示的名字(单数形式)
        verbose_name_plural = verbose_name  # 效果同上，是复数形式


class Queue(models.Model):
    def __str__(self):
        return self.name

    uid = models.AutoField(primary_key=True)
    user = models.CharField(max_length=50)  # 计划任务创建人
    hostname = models.CharField(max_length=50)
    name = models.CharField(max_length=50)  # 计划名
    time = models.CharField(max_length=50)  # 创建时间
    status = models.CharField(max_length=50, default='')  # 执行状态
    result = models.TextField()  # 执行结果

    class Meta:
        verbose_name = "队列信息"  # 定义该实体类在 admin 中显示的名字(单数形式)
        verbose_name_plural = verbose_name  # 效果同上，是复数形式


class linuxTemplate(models.Model):
    uid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)  # linux命令模板名称
    content = models.TextField()  # linux命令


class dataBaseGroup(models.Model):
    def __str__(self):
        return self.name

    uid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, verbose_name='名称', null=True, blank=True)

    class Meta:
        verbose_name = "数据库类型"  # 定义该实体类在 admin 中显示的名字(单数形式)
        verbose_name_plural = verbose_name  # 效果同上，是复数形式


class dataBase(models.Model):
    def __str__(self):
        return self.name

    uid = models.AutoField(primary_key=True)
    dataGroup = models.ForeignKey(dataBaseGroup, null=True, on_delete=models.CASCADE, verbose_name='数据库类型')
    name = models.CharField(max_length=50, verbose_name='名称', null=True, blank=True)
    ip = models.CharField(max_length=50, verbose_name='ip')
    user = models.CharField(max_length=50, verbose_name='用户名', null=True, blank=True)  # 用户账号
    password = models.CharField(max_length=50, verbose_name='密码', null=True, blank=True)  # 密码
    port = models.CharField(max_length=10, verbose_name="端口", null=True, blank=True)  # 端口
    edition = models.CharField(max_length=50, verbose_name='版本', null=True, blank=True)
    remark = models.CharField(max_length=50, verbose_name='备注', null=True, blank=True)  # 备注
    group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='分组')

    class Meta:
        verbose_name = "数据库信息"  # 定义该实体类在 admin 中显示的名字(单数形式)
        verbose_name_plural = verbose_name  # 效果同上，是复数形式


class UrlMgm(models.Model):
    def __str__(self):
        return self.name

    uid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, verbose_name='名称')
    group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='分组')
    url = models.CharField(max_length=200, verbose_name='url地址', null=True, blank=True)
    user = models.CharField(max_length=50, verbose_name='账号', null=True, blank=True)
    password = models.CharField(max_length=50, verbose_name='密码', null=True, blank=True)  # 密码

    class Meta:
        verbose_name = "网址记录"  # 定义该实体类在 admin 中显示的名字(单数形式)
        verbose_name_plural = verbose_name


class UrlMgmgroup(models.Model):
    def __str__(self):
        return self.name

    uid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, verbose_name='url分组名称')
    url = models.ManyToManyField(UrlMgm, blank=True, verbose_name='url')

    class Meta:
        verbose_name = "网址记录权限控制"  # 定义该实体类在 admin 中显示的名字(单数形式)
        verbose_name_plural = verbose_name


class UsersGroup(models.Model):  # 添加用户分组类
    def __str__(self):
        return self.name

    uid = models.AutoField(primary_key=True, verbose_name='ID')  # 自增id
    name = models.CharField(max_length=30, verbose_name='分组名称', unique=True)
    hostgroup = models.ManyToManyField(Group, verbose_name='机器组', blank=True)  # 设置用户组可以拥有哪些机器组的权限
    host = models.ManyToManyField(PassWord, verbose_name='特定机器', blank=True)
    urlgroup = models.ForeignKey(UrlMgmgroup, verbose_name='Url分组信息', blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "用户组"  # 定义该实体类在 admin 中显示的名字(单数形式)
        verbose_name_plural = verbose_name


class Users(models.Model):  # 添加用户类
    uid = models.AutoField(primary_key=True)
    user = models.CharField(max_length=30, unique=True)  # 唯一索引
    fullName = models.CharField(max_length=30, verbose_name='全名')
    password = models.CharField(max_length=30)
    user_group = models.ForeignKey(UsersGroup, null=True, on_delete=models.CASCADE, verbose_name='用户分组',
                                   blank=True)  # 一对多
    remark = models.ManyToManyField(remarks, verbose_name='备注信息', blank=True)  # 多对多

    def __str__(self):
        return self.user

    class Meta:
        verbose_name = "用户信息"  # 定义该实体类在 admin 中显示的名字(单数形式)
        verbose_name_plural = verbose_name  # 效果同上，是复数形式


class supervisor(models.Model):
    id = models.AutoField(primary_key=True)
    ip = models.ForeignKey(PassWord, verbose_name='ip', on_delete=models.CASCADE)
    user = models.CharField(max_length=30, default='user', blank=True, verbose_name='账号')
    password = models.CharField(max_length=30, default='123', blank=True, verbose_name='密码')
    port = models.IntegerField(blank=True, default=9001, verbose_name='端口')  # 端口

    def __str__(self):
        return self.ip.ip

    class Meta:
        verbose_name = "supervisor"  # 定义该实体类在 admin 中显示的名字(单数形式)
        verbose_name_plural = verbose_name


templates/add_host.html
{% extends 'content.html' %}
{% block h %}
    <div id="page-wrapper">
        <div class="header">
            <h3 class="page-header">
                添加服务器
            </h3>
        </div>

        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="card-title">
                        <div class="title">添加单台</div>
                    </div>
                </div>
                <div class="panel-body">
                    <form action="{% url 'add' %}" method="post" class="form-horizontal">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">服务器名:</label>
                            <div class="col-sm-10">
                                {{ form.hostname }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">系统:</label>
                            <div class="col-sm-10">
                                {{ form.system }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">外网IP:</label>
                            <div class="col-sm-10">
                                {{ form.ip }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">内网IP:</label>
                            <div class="col-sm-10">
                                {{ form.intranet_ip }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Root账号:</label>
                            <div class="col-sm-10">
                                {{ form.user }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Root密码:</label>
                            <div class="col-sm-10">
                                {{ form.password }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">端口:</label>
                            <div class="col-sm-10">
                                {{ form.port }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">分组:</label>
                            <div class="col-sm-10">
                                {{ form.group }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">所属项目:</label>
                            <div class="col-sm-10">
                                {{ form.projectName }}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-50 col-sm-10">
                                <button type="submit" style="margin-left: 0%;" class="btn btn-primary">添加</button>
                            </div>
                        </div>
                        <div class="form-group">
                            <div style="color:red" class="col-sm-offset-50 col-sm-10">
                                <p style="color: red;">{{ mes }}</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>


        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="card-title">
                        <div class="title">批量导入</div>
                    </div>
                </div>
                <div class="panel-body">
                    <!-- import excel  -->
                    <form enctype="multipart/form-data" action="/imp/" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            {#                            <label for="exampleInputFile">File input</label>#}
                            <input type="file" id="exampleInputFile" name="myfile">
                            <p class="help-block">只支持Excel文档导入,模板可以重置密码后下载查看,相同IP不会重复添加</p>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-50 col-sm-10">
                                <button type="submit" style="margin-left: -10px;" class="btn btn-primary">提交</button>
                            </div>
                        </div>
                    </form>
                    <div class="form-group">
                        <div style="color:red" class="col-sm-offset-50 col-sm-10">
                            <p style="color: red;">{{ mes }}</p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <script src="/static/assets/js/jquery-1.10.2.js"></script>
    <script src="/static/assets/js/bootstrap.min.js"></script>
{% endblock %}

templates/edit_project.html
{% extends 'content.html' %}
{% block h %}
    <div id="page-wrapper">
        <div class="header">
            <h3 class="page-header">
                项目模板
            </h3>
        </div>

        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="card-title">
                        <div class="title">编辑模板</div>
                    </div>
                </div>
                <div class="panel-body">
                    <div>
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                <tr>
                                    <th>项目名称</th>
                                    <th>日志路径</th>
                                    <th>执行语句</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for x in value %}
                                    <tr class="even gradeC">
                                        <td>{{ x.obj_name }}</td>
                                        <td>{{ x.obj_log }}</td>
                                        <td>
                                            <pre style="word-wrap: break-word; table-layout: fixed; width: 100%">{{ x.obj_text }}</pre>
                                        </td>
                                        <td>
                                            <button class="btn default" id="edit" value="{{ x.uid }}" onclick="edit({{ x.uid }})"
                                                    style="margin-left:0;color:#fff;background-color:#409eff;border-color:#409eff;border-style:solid">
                                                修改
                                            </button>
                                            <button class="btn default" onclick="if (confirm('确定要删除吗？')) {window.location.href='{% url 'obj_del' x.uid %}'}"
                                                    style="margin-left:0;color:#fff;background-color:#c20003;border-color:#c20006;border-style:solid">
                                                删除
                                            </button>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <form id="fom" action="{% url 'edit_project' %}" method="post" class="form-horizontal">
                            {% csrf_token %}
                            <div class="sub-title" style="margin-left: 0%">项目名称:</div>
                            <div>
                                {{ form.obj_name }}
                            </div>
                            <div class="sub-title" style="margin-left: 0%">日志路径:</div>
                            <div>
                                {{ form.obj_log }}
                            </div>
                            <div class="sub-title" style="margin-left: 0%">执行语句:</div>
                            <div>
                                {{ form.obj_text }}
                            </div>
                            <p hidden id="uid"></p>
                            <br>
                            <p style="color: red;" id="mes"></p>
                            <button id="btn" type="submit"
                                    style="margin-left: 0;"
                                    class="btn btn-info">添加
                            </button>
                        </form>
                        <div hidden id="ediv">
                            <button id="ebtn" class="btn btn-danger"
                                    style="margin-left: 0;">修改
                            </button>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="/static/assets/js/jquery-1.10.2.js"></script>
    <script src="/static/assets/js/bootstrap.min.js"></script>
    <script>
        function edit(uid) {
            $.ajax(
                {
                    url: '/obj_update/',
                    data: {'uid': uid},
                    type: 'post',
                    dataType: 'json',
                    async: 'true',
                    success: function (data) {
                        $('#id_obj_name').val(data['obj_name']);
                        $('#id_obj_log').val(data['obj_log']);
                        $('#id_obj_text').val(data['obj_text']);
                        $('#uid').val(uid);
                        $('#btn').hide();
                        $('#ediv').show();
                    },
                    error: function (xhr, error) {
                        console.log('失败');
                        console.log(error);
                    }
                }
            )
        }

        $(function () {
            var ebtn = $('#ebtn');
            ebtn.click(function () {
                var name = $('#id_obj_name').val();
                var log = $('#id_obj_log').val();
                var text = $('#id_obj_text').val();
                var uid = $('#uid').val();
                $.ajax(
                    {
                        url: '/obj_hd/',
                        data: {'obj_name': name, 'obj_text': text, 'uid': uid, 'obj_log': log},
                        type: 'post',
                        dataType: 'json',
                        async: 'true',
                        success: function (data) {
                            alert("恭喜你，修改成功")
                            window.location.reload();
                        },
                        error: function (xhr, error) {
                            $('#mes').text("修改失败")
                        }
                    }
                )
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            $('#id_obj_log').css("width", "20.5%");
            $('#edit_project').attr('class', 'active-menu')
        })

    </script>
{% endblock %}

templates/form.html
{% extends 'content.html' %}
{% block h %}
    <div id="page-wrapper">
        <div class="header">
            <h3 class="page-header">
                添加服务器
            </h3>
        </div>

        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="card-title">
                        <div class="title">添加单台</div>
                    </div>
                </div>
                <div class="panel-body">
                    <form action="{% url 'add' %}" method="post" class="form-horizontal">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">服务器名:</label>
                            <div class="col-sm-10">
                                {{ form.hostname }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">系统:</label>
                            <div class="col-sm-10">
                                {{ form.system }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">外网IP:</label>
                            <div class="col-sm-10">
                                {{ form.ip }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">内网IP:</label>
                            <div class="col-sm-10">
                                {{ form.intranet_ip }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Root账号:</label>
                            <div class="col-sm-10">
                                {{ form.user }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Root密码:</label>
                            <div class="col-sm-10">
                                {{ form.password }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">用户:</label>
                            <div class="col-sm-10">
                                {{ form.normal_user }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">密码:</label>
                            <div class="col-sm-10">
                                {{ form.normal_pwd }}
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">端口:</label>
                            <div class="col-sm-10">
                                {{ form.port }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">分组:</label>
                            <div class="col-sm-10">
                                {{ form.group }}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-50 col-sm-10">
                                <button type="submit" style="margin-left: 0%;" class="btn btn-default">添加</button>
                            </div>
                        </div>
                        <div class="form-group">
                            <div style="color:red" class="col-sm-offset-50 col-sm-10">
                                <p style="color: red;">{{ mes }}</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>


        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="card-title">
                        <div class="title">批量导入</div>
                    </div>
                </div>
                <div class="panel-body">
                    <!-- import excel  -->
                    <form enctype="multipart/form-data" action="/imp/" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            {#                            <label for="exampleInputFile">File input</label>#}
                            <input type="file" id="exampleInputFile" name="myfile">
                            <p class="help-block">只支持Excel文档导入,模板可以重置密码后下载查看,相同IP不会重复添加</p>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-50 col-sm-10">
                                <button type="submit" style="margin-left: -10px;" class="btn btn-primary">提交</button>
                            </div>
                        </div>
                    </form>
                    <div class="form-group">
                        <div style="color:red" class="col-sm-offset-50 col-sm-10">
                            <p style="color: red;">{{ mes }}</p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <script src="/static/assets/js/jquery-1.10.2.js"></script>
    <script src="/static/assets/js/bootstrap.min.js"></script>
{% endblock %}